name: crawler

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  crawler:
    runs-on: ubuntu-latest

    # env:
    #   HEMNET_URL: ${{vars.HEMNET_URL}}
    #   KEYWORDS_REQUIRED: ${{vars.KEYWORDS_REQUIRED}}
    #   KEYWORDS_OPTIONAL: ${{vars.KEYWORDS_OPTIONAL}}
    #   EMAIL_HOST: ${{secrets.EMAIL_HOST}}
    #   EMAIL_USER: ${{secrets.EMAIL_USER}}
    #   EMAIL_PASS: ${{secrets.EMAIL_PASS}}
    #   EMAIL_RECIEVERS: ${{secrets.EMAIL_RECIEVERS}}

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Crawl Hemnet
        run: |
          npm run prod
